/**
 * Created by zsh on 2016/3/11.
 */
export const RECEIVE_WX_CONFIG  = 'RECEIVE_WX_CONFIG'
export const SET_LAND_PAGE  = 'SET_LAND_PAGE'
/*********问题**********/
export const RECEIVE_HOT_QUESTION_LIST  = 'RECEIVE_HOT_QUESTION_LIST'
export const RECEIVE_QUESTION_INFO  = 'RECEIVE_QUESTION_INFO'
export const REQUEST_LISTEN_INFO  = 'REQUEST_LISTEN_INFO'
export const RECEIVE_LISTEN_INFO  = 'RECEIVE_LISTEN_INFO'
export const RECEIVE_SAVE_VOICE  = 'RECEIVE_SAVE_VOICE'

/*********导师**********/
export const RECEIVE_TUTOR_LIST  = 'RECEIVE_TUTOR_LIST'
export const RECEIVE_TUTOR_INFO  = 'RECEIVE_TUTOR_INFO'
export const RECEIVE_TUTOR_ANSWER_LIST  = 'RECEIVE_TUTOR_ANSWER_LIST'
export const REQUEST_PREPAY_INFO  = 'REQUEST_PREPAY_INFO'
export const RECEIVE_PREPAY_INFO  = 'RECEIVE_PREPAY_INFO'

/*********我的**********/
//获取到用户消息
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO';
export const RECEIVE_OTHER_USER_INFO = 'RECEIVE_OTHER_USER_INFO';
//获取听过的问题列表
export const REQUEST_LISTENED = 'REQUEST_LISTENED';
export const LISTENED_COMPLETED = 'LISTENED_COMPLETED';
export const RECEIVE_LISTENED = 'RECEIVE_LISTENED';
//获取我问的问题列表
export const REQUEST_I_ASKED = 'REQUEST_I_ASKED';
export const RECEIVE_I_ASKED = 'RECEIVE_I_ASKED';
export const I_ASKED_COMPLETED = 'I_ASKED_COMPLETED';

//获取问我的问题列表
export const REQUEST_ASKED_ME = 'REQUEST_ASKED_ME';
export const CLEAR_ASKED_ME = 'CLEAR_ASKED_ME';
export const RECEIVE_ASKED_ME = 'RECEIVE_ASKED_ME';
export const ASKED_ME_COMPLETED = 'ASKED_ME_COMPLETED';




